name: NextJS Pipeline

on: 
  push:
    branches: ["master"]
    
jobs: 
  job1:
      name: job1
      runs-on: ubuntu-latest
      steps:
        - name: First step
          run: echo "step 1"
        - name: create
          run: touch job1.txt
        - name: verify2
          run: ls -l

  job2:
      name: job2
      runs-on: ubuntu-latest
      steps:
        - name: First step job2
          run: echo "HEY" > job2.txt
        - name: Verify
          run: cat job2.txt

  job3:
    name: job3
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: verifyy
        run: ls -l
          